version: '3'

services:
  # 配置数据库
  mysql:
    image: mysql:5.7
    restart: always
    container_name: "mysql_5_7"
    environment:
      MYSQL_ROOT_PASSWORD: idorp123456
    ports:
      - 3306:3306
    volumes: 
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    networks:
      - tt-net
  # 配置phpmyadmin 
  phpmyadmin:
    image: library/phpmyadmin
    #restart: always
    container_name: "phpmyadmin"
    ports:
      - 9999:80
    links:
      - mysql:db
    networks:
      - tt-net

  # 配置redis
  redis:
    image: redis:3
    container_name: "redis3"
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ./redis/data:/data
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes  --requirepass idorp123456
    networks:
      - tt-net


  # 配置openresty   extra_hosts=给容器添加hosts
  # extra_hosts:
  #   - dev.idorp.com:127.0.0.1
  openresty:
    image: openresty/openresty:focal
    container_name: "openresty_focal"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./openresty/conf:/etc/nginx/conf.d
      - ./openresty/data:/data
      - ./openresty/logs:/usr/local/openresty/nginx/logs
    networks:
      - tt-net

  # 配置EMQ
  emq:
    image: emqx/emqx:4.2.1
    container_name: "emq_4_2_1"
    #restart: always
    ports:
      - 1883:1883
      - 18083:18083
    volumes: 
      - ./emq/log:/opt/emqx/log
    networks:
      - tt-net
    
networks: 
  tt-net: 
    driver: bridge

        
        