version: '3'

services:
  # 配置数据库   skip-name-resolve  解决通过dns连接数据库慢的问题
  mysql:
    image: mysql:5.7
    restart: always
    container_name: "mysql_5_7"
    environment:
      - MYSQL_ROOT_PASSWORD=idorp123456
    ports:
      - 3306:3306
    volumes: 
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf/conf.d:/etc/mysql/conf.d
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --lower-case-table-names=1
      --skip-name-resolve  
    networks:
      - tt-net

  # 配置phpmyadmin 
  phpmyadmin:
    image: library/phpmyadmin
    #restart: always
    container_name: "phpmyadmin"
    ports:
      - 9999:80
    links:
      - mysql:db
    networks:
      - tt-net
    environment:
      # 开启连接外部数据的IP选择框
      - PMA_ARBITRARY=1

  # 配置redis
  redis:
    image: redis:7
    container_name: "redis7"
    restart: always
    ports:
      - 6379:6379
    volumes: 
      - ../redis/data:/data
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --appendonly yes  --requirepass idorp123456
    networks:
      - tt-net

  # 配置openresty   extra_hosts=给容器添加hosts
  # extra_hosts:
  #   - dev.idorp.com:127.0.0.1
  openresty:
    image: openresty/openresty:focal
    container_name: "openresty_focal"
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../openresty/conf:/etc/nginx/conf.d
      - ../openresty/data:/data
      - ../openresty:/usr/local/openresty/nginx/conf/nginx.conf
      - ../openresty/logs:/usr/local/openresty/nginx/logs
    networks:
      - tt-net

  # 配置EMQ
  emq:
    image: emqx/emqx:4.2.1
    container_name: "emq_4_2_1"
    #restart: always
    ports:
      - 1883:1883
      - 8083:8083
      - 18083:18083
    volumes: 
      - ../emq/log:/opt/emqx/log
    networks:
      - tt-net

      # 配置portainer 容器管理器
  dockerManager:
    image: portainer/portainer-ce:latest
    #restart: always
    container_name: "dockerManager"
    ports:
      - 9000:9000
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - ../dockerManager/data:/data
    networks:
      - tt-net

  #FLINK配置
  jobmanager:
    image: flink:latest
    expose:
      - "6123"
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - tt-net

  taskmanager:
    image: flink:latest
    expose:
      - "6121"
      - "6122"
    depends_on:
      - jobmanager
    command: taskmanager
    links:
      - "jobmanager:jobmanager"
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    networks:
      - tt-net

  #jenkins 配置
  jenkins:
    image: 'jenkins/jenkins'
    container_name: jenkins
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '9998:8080'
      - '50000:50000'
    volumes:
      - '/etc/localtime:/etc/localtime'
      - '/home/data/jenkins:/var/jenkins_home'
    networks:
      - tt-net
      
  #redmine 配置    
  redmine:
    image: redmine:4.2.7-bullseye
    container_name: redmine
    # restart: always
    ports:
      - 3000:3000
    environment:
      - VIRTUAL_HOST=127.0.0.1
      - VIRTUAL_NETWORK=nginx-proxy
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=127.0.0.1
      - LETSENCRYPT_EMAIL=365328730@qq.com
      - REDMINE_DB_MYSQL=mysql
      - REDMINE_DB_USERNAME=root
      - REDMINE_DB_PASSWORD=idorp123456
      - REDMINE_DB_PORT=3306
      - REDMINE_DB_NAME=redmine
      - REDMINE_SECRET_KEY_BASE=sunzhicheng@P0SSW0RD
      
    volumes:
      - ../redmine/config/configuration.yml:/usr/src/redmine/config/configuration.yml
      - ../redmine/files:/usr/src/redmine/files
      - ../gogs/data:/usr/src/redmine/gogs-repositories
    depends_on:
      - mysql
    networks:
      - tt-net

  gogs:
    #restart: always # 自动重启
    image: gogs/gogs
    container_name: gogs
    ports:
      - "6022:22" # ssh 端口
      - "6030:3000" # Web 访问端口
    volumes:
      - ../gogs/data:/data/git/gogs-repositories # 数据存储
    networks:
      - tt-net  

  dgiot:
    image: dgiot/dgiot:4.4.5
    container_name: iot
    ports:
      - "6040:5080" # ssh 端口
    networks:
      - tt-net  
 
  tb:
    # restart: always
    image: "thingsboard/tb-postgres"
    container_name: tb_iot
    ports:
      - "6090:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ../thingsboard/data:/data
      - ../thingsboard/logs:/var/log/thingsboard
# volumes:
#   mytb-data:    #可在所有服务中调用
#     external: true   #如果设置为 true 则 docker-compose up 不会尝试创建它, 如果它不存在则引发错误
#   mytb-logs:
#     external: true
networks: 
  tt-net: 
    driver: bridge

        
        